# Basic
title: 连松青
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: zteman
# 头像里面的描述
avatarDesc: Android / 全栈工程师
url: "http://zteman.com"

# Comment
comment:
    # disqus: zteman
    # duoshuo: zteman
    # cloudTie: zteman

# Social
social:
    weibo: 5691810696
    github: zteman
    # twitter: 
    mail: g.lsqboy@gmail.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 353a7759055b69a20b45dd701e6b0b70

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-84134159-3
#    host: auto


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
plugins: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


